USE [master]
GO

/****** Object:  Database [NuclearMotors]    Script Date: 22/11/2014 8:40:41 PM ******/
DROP DATABASE [NuclearMotors]
GO

/****** Object:  Database [NuclearMotors]    Script Date: 22/11/2014 8:40:41 PM ******/
CREATE DATABASE [NuclearMotors]
 CONTAINMENT = NONE
GO

ALTER DATABASE [NuclearMotors] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NuclearMotors].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NuclearMotors] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NuclearMotors] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NuclearMotors] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NuclearMotors] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NuclearMotors] SET ARITHABORT OFF 
GO

ALTER DATABASE [NuclearMotors] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NuclearMotors] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NuclearMotors] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NuclearMotors] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NuclearMotors] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NuclearMotors] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NuclearMotors] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NuclearMotors] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NuclearMotors] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NuclearMotors] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NuclearMotors] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NuclearMotors] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NuclearMotors] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NuclearMotors] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NuclearMotors] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NuclearMotors] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NuclearMotors] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NuclearMotors] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NuclearMotors] SET RECOVERY FULL 
GO

ALTER DATABASE [NuclearMotors] SET  MULTI_USER 
GO

ALTER DATABASE [NuclearMotors] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NuclearMotors] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NuclearMotors] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NuclearMotors] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NuclearMotors] SET  READ_WRITE 
GO


